# Generated by Django 3.0.3 on 2020-05-08 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admitted_Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_no', models.IntegerField()),
                ('password', models.CharField(max_length=1000000)),
            ],
        ),
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Records',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_1_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('personal_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Personal_Detail')),
            ],
        ),
    ]
