# Generated by Django 3.0.3 on 2020-05-08 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_1_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentor_name', models.CharField(max_length=50)),
                ('mentor_email', models.EmailField(max_length=254)),
                ('mentor_password', models.CharField(max_length=50)),
                ('mentor_phone_no', models.IntegerField()),
                ('mentor_previous_batch', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mentor_Mentee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Mentor')),
            ],
        ),
        migrations.DeleteModel(
            name='Exam_Records',
        ),
    ]
