# Generated by Django 3.0.3 on 2020-05-08 21:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0002_auto_20200509_0241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Placement_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('bond', models.CharField(max_length=100)),
                ('ctc', models.CharField(max_length=100)),
                ('hr_email', models.EmailField(max_length=254)),
                ('placed_through', models.CharField(max_length=100)),
                ('offer_letter', models.CharField(max_length=1000)),
                ('details', models.CharField(max_length=10000)),
                ('verified', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Personal Details', 'Personal Details'), ('Exam Details', 'Exam Details'), ('Internship Details', 'Internship Details'), ('Placement Details', 'Placement Details'), ('Other', 'Other')], max_length=30)),
                ('message', models.CharField(max_length=10000)),
                ('datetime', models.DateTimeField()),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
        migrations.CreateModel(
            name='Internship_Details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=40)),
                ('position', models.CharField(max_length=100)),
                ('duration_start', models.DateField()),
                ('duration_end', models.DateField()),
                ('certificate', models.CharField(max_length=1000)),
                ('intern_eval', models.CharField(max_length=1000)),
                ('verified', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
    ]
