# Generated by Django 3.0.3 on 2020-05-08 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0004_auto_20200509_0247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10)),
                ('dob', models.DateField()),
                ('ph_no', models.IntegerField()),
                ('parent_ph_no', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('profile_photo', models.CharField(max_length=100)),
                ('department', models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('ETRX', 'ETRX'), ('EXTC', 'EXTC')], max_length=10)),
                ('year', models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2)),
                ('division', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2)),
                ('roll_no', models.IntegerField()),
                ('verified', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
        migrations.CreateModel(
            name='Exam_Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem_1_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_1_dop', models.CharField(default=None, max_length=40)),
                ('sem_1_atkt', models.IntegerField(default=0)),
                ('sem_1_sgpi', models.FloatField(default=0)),
                ('sem_1_attempts', models.IntegerField(default=0)),
                ('sem_2_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_2_dop', models.CharField(default=None, max_length=40)),
                ('sem_2_atkt', models.IntegerField(default=0)),
                ('sem_2_sgpi', models.FloatField(default=0)),
                ('sem_2_attempts', models.IntegerField(default=0)),
                ('sem_3_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_3_dop', models.CharField(default=None, max_length=40)),
                ('sem_3_atkt', models.IntegerField(default=0)),
                ('sem_3_sgpi', models.FloatField(default=0)),
                ('sem_3_attempts', models.IntegerField(default=0)),
                ('sem_4_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_4_dop', models.CharField(default=None, max_length=40)),
                ('sem_4_atkt', models.IntegerField(default=0)),
                ('sem_4_sgpi', models.FloatField(default=0)),
                ('sem_4_attempts', models.IntegerField(default=0)),
                ('sem_5_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_5_dop', models.CharField(default=None, max_length=40)),
                ('sem_5_atkt', models.IntegerField(default=0)),
                ('sem_5_sgpi', models.FloatField(default=0)),
                ('sem_5_attempts', models.IntegerField(default=0)),
                ('sem_6_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_6_dop', models.CharField(default=None, max_length=40)),
                ('sem_6_atkt', models.IntegerField(default=0)),
                ('sem_6_sgpi', models.FloatField(default=0)),
                ('sem_6_attempts', models.IntegerField(default=0)),
                ('sem_7_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_7_dop', models.CharField(default=None, max_length=40)),
                ('sem_7_atkt', models.IntegerField(default=0)),
                ('sem_7_sgpi', models.FloatField(default=0)),
                ('sem_7_attempts', models.IntegerField(default=0)),
                ('sem_8_cleared', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default=None, max_length=3)),
                ('sem_8_dop', models.CharField(default=None, max_length=40)),
                ('sem_8_atkt', models.IntegerField(default=0)),
                ('sem_8_sgpi', models.FloatField(default=0)),
                ('sem_8_attempts', models.IntegerField(default=0)),
                ('verified', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3)),
                ('admitted_student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triple_M.Admitted_Student')),
            ],
        ),
    ]
