# Generated by Django 3.0.3 on 2020-05-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0005_exam_record_personal_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personal_detail',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='personal_detail',
            name='last_name',
        ),
        migrations.AddField(
            model_name='admitted_student',
            name='first_name',
            field=models.CharField(default='None', max_length=20),
        ),
        migrations.AddField(
            model_name='admitted_student',
            name='last_name',
            field=models.CharField(default='None', max_length=20),
        ),
    ]
