# Generated by Django 3.0.3 on 2020-05-09 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0006_auto_20200509_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personal_detail',
            name='address',
            field=models.CharField(default=None, max_length=1000),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('ETRX', 'ETRX'), ('EXTC', 'EXTC')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='division',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], default=None, max_length=2),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='dob',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='email',
            field=models.EmailField(default=None, max_length=254),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='gender',
            field=models.CharField(choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], default=None, max_length=10),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='parent_ph_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='ph_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='profile_photo',
            field=models.CharField(default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='roll_no',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='year',
            field=models.CharField(choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], default=None, max_length=2),
        ),
    ]
