# Generated by Django 3.0.3 on 2020-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0008_exam_record_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_cleared',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_dop',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='verified',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='', max_length=3),
        ),
    ]
