# Generated by Django 3.0.3 on 2020-05-10 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0009_auto_20200510_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_record',
            name='verified',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
    ]
