# Generated by Django 3.0.3 on 2020-05-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0011_auto_20200510_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_1_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_2_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_3_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_4_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_5_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_6_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_7_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_atkt',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_attempts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_cleared',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_dop',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='sem_8_sgpi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='exam_record',
            name='verified',
            field=models.CharField(blank=True, choices=[('YES', 'YES'), ('NO', 'NO')], max_length=3, null=True),
        ),
    ]
