# Generated by Django 3.0.3 on 2020-05-12 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0012_auto_20200510_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam_record',
            name='verified',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='address',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='department',
            field=models.CharField(blank=True, choices=[('IT', 'IT'), ('COMPS', 'COMPS'), ('ETRX', 'ETRX'), ('EXTC', 'EXTC')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='division',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='dob',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='gender',
            field=models.CharField(blank=True, choices=[('MALE', 'MALE'), ('FEMALE', 'FEMALE')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='parent_ph_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='ph_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='profile_photo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='roll_no',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='personal_detail',
            name='year',
            field=models.CharField(blank=True, choices=[('FE', 'FE'), ('SE', 'SE'), ('TE', 'TE'), ('BE', 'BE')], max_length=2, null=True),
        ),
    ]
