# Generated by Django 3.0.3 on 2020-05-12 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0013_auto_20200512_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_detail',
            name='duration_end',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='internship_detail',
            name='duration_start',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
