# Generated by Django 3.0.3 on 2020-05-15 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0014_auto_20200512_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internship_detail',
            name='duration_end',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='internship_detail',
            name='duration_start',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
    ]
