# Generated by Django 3.0.3 on 2020-05-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('triple_M', '0021_auto_20200516_1900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_1_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_2_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_3_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_4_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_5_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_6_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_7_marksheet',
        ),
        migrations.RemoveField(
            model_name='exam_record',
            name='sem_8_marksheet',
        ),
    ]
